version: 2.1

jobs:
  build-react:
    docker:
      - image: cimg/node:20.10.0
    working_directory: ~/project/ecom-catalog-react
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: "Build React app"
          command: npm run build
      - store_artifacts:
          path: dist

workflows:
  build-apps:
    jobs:
      - build-react
